### ISSUE TITLE
Caching BMC e2e results for an hour can cause alerting problems

### ISSUE THREAD

**Issue by nkinkade** [m-lab/reboot-service#40]
Currently, the reboot-service (reboot-api Deployment) caches a BMC e2e test result for an hour, and for the next hour will advertise that up or failed state via the `reboot_e2e_result` metric. Recently we have run up against some cases where we get a `BMC_CredentialsNotFound` alert, when indeed those credentials are in GCD. What is apparently happening here is that the `reboot_e2e_result` metric is returning the same cached (failed) state for an hour, but no alert is firing because the site/machine is in GMX mode. The operator fixes all the problems and takes the site/machine out of GMX. However, when the alert is next evaluated, it finds the cached failed state for the `reboot_e2e_result` metric _and_ finds that the site/machine is now not in GMX, and an alert fires. We need to figure out some way to get around this likelihood. 

One possible way would be to only cache positive results for checks, and a failed state would cause the service to probe the DRAC every minute looking for resolution. However, @robertodauria seems to recall that the caching middleware package in use did not support selective caching. Maybe it does now?

**Comment by robertodauria** [comment]
https://github.com/victorspringer/http-cache

It was on the roadmap but it doesn't look like the project is being actively developed anymore. Bummer.

Would changing the alert so that it only fires after the condition has been true for more than 1hr resolve this? It's not crucial to know that a DRAC is down or credentials are missing _immediately_, I think. In that case, what would happen is:
- Credentials are added to Datastore
- The site is taken out of GMX - the alert condition becomes true
- Within an hour the e2e result is updated, the alert condition becomes false
- The alert doesn't fire

**Comment by nkinkade** [comment]
That sounds like a good solution. You are right, a DRAC's credentials not being datastore doesn't need to be reported after just 5m. Indeed, I see that `BMC_ConnectionFailed` won't fire for an entire day of the condition being true. I'm thinking we should update all the BMC alerts to not fire for 1d.
